const data = [
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/1.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "Black Adam",
        status: "Subscription",
        rating: 8.5,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/2.jpg"),
        link: "/watch",
        category: "horror",
        title: "Scream",
        status: "Free",
        rating: 7.4,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/3.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "Creator",
        status: "Subscription",
        rating: 7.5,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/4.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "X-Men",
        status: "Subscription",
        rating: 7.7,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/5.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "Avatar",
        status: "Subscription",
        rating: 9.1,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/6.jpg"),
        link: "/watch",
        category: "scientific-fantasy",
        title: "Interstellar",
        status: "Subscription",
        rating: 10.0,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/7.jpg"),
        link: "/watch",
        category: "scientific-fantasy",
        title: "Passengers",
        status: "Subscription",
        rating: 8.1,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/8.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "Avengers:  Endgame",
        status: "Subscription",
        rating: 9.6,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/9.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "Avatar 2",
        status: "Subscription",
        rating: 8.9,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/most_watched/10.jpg"),
        link: "/watch",
        category: "horror",
        title: "Wednesday",
        status: "free",
        rating: 8.7,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/11.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "Lord of the rings",
        status: "Subscription",
        rating: 9.2,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "movie",
        img: require("@/assets/img/most_watched/12.jpg"),
        link: "/watch",
        category: "books",
        title: "Harry Potter",
        status: "Subscription",
        rating: 9.4,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/1.jpg"),
        link: "/watch",
        category: "documental",
        title: "Cosmos",
        status: "Subscription",
        rating: 7.4,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/2.jpg"),
        link: "/watch",
        category: "horror",
        title: "Squid Game",
        status: "Subscription",
        rating: 8.3,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/3.jpg"),
        link: "/watch",
        category: "history",
        title: "Merlin",
        status: "Subscription",
        rating: 7.1,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/4.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "Phines & Ferb",
        status: "free",
        rating: 7.4,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/5.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "Loki",
        status: "Subscription",
        rating: 8.6,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/6.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "WandaVision",
        status: "Subscription",
        rating: 8.6,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/7.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "She Hulk",
        status: "Subscription",
        rating: 5.4,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/8.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "The flash",
        status: "Subscription",
        rating: 6.7,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/9.jpg"),
        link: "/watch",
        category: "horror",
        title: "Stranger Things",
        status: "Subscription",
        rating: 7.6,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/10.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "Game of Thrones",
        status: "Subscription",
        rating: 7.4,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/11.jpg"),
        link: "/watch",
        category: "fantastic",
        title: "Green Arrow",
        status: "Subscription",
        rating: 7.4,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
    {
        id: Date.now(),
        type: "series",
        img: require("@/assets/img/series/12.jpg"),
        link: "/watch",
        category: "books",
        title: "Sherlock Holmes",
        status: "Subscription",
        rating: 7.4,
        descr: {
            date: "2023, USA",
            info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        },
    },
];

export default data;
